services:
  app:
    build: .
    container_name: volei-draft-app
    restart: unless-stopped

    ports:
      - "3000:5000"

    volumes:
      - .:/app

    env_file:
      - .env

    environment:
      FLASK_ENV: production

    command: >
      gunicorn
      -k gevent
      -w 1
      -b 0.0.0.0:5000
      app:app
