services:
  web-dev:
    build: .
    container_name: volei-draft-dev
    ports:
      - "5001:5000"   # ⚠️ Porta do dev
    env_file:
      - .env.dev
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - /srv/volei_draft:/app
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - dev-network

networks:
  dev-network:
    name: volei-draft-dev-network
